# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - hughjonesd/rcheology

after_success:
  - Rscript -e 'covr::codecov(function_exclusions = "\\.onLoad")'

after_failure:
  - Rscript -e 'devtools::install(); devtools::test()'
