---
title: "apicheck Performance Tests"
author: "David Hugh-Jones <davidhughjones@gmail.com>"
date: "`r Sys.Date()`"
output: rmarkdown::html_document

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

# Speed tests

On my Macbook Air, standard broadband connection.


`clipr` is a small package with few versions. `mice` is a larger package which requires compilation, with more
dependencies.


```{r}
library(apicheck)
library(microbenchmark)
library(ggplot2)
library(dplyr)
options(repos = "https://cran.rstudio.com")

make_test <- function(fn, search, min_version = NA) {
  if (is.na(min_version)) min_version <- NULL
  bquote(when_fn_exists(.(fn), search = .(search), min_version = .(min_version)))
}

fns <- c("clipr::dr_clipr", "mice::ncc")
min_versions <- c(NA, "2.20")
args <- expand.grid(
        fn          = fns,
        search      = c("binary", "forward", "backward", "all", "parallel"), 
        stringsAsFactors = FALSE
      )
args$min_version <- min_versions[match(args$fn, fns)]

tests <- do(rowwise(args), expr = make_test(.$fn, .$search, .$min_version)) %>% pull(expr)

as.character(tests)
```

## Pre-downloaded

```{r, cache = TRUE}
# cache packages:
invisible(mapply(when_fn_exists, fn = fns, min_version = min_versions, search = "all"))


cached <- microbenchmark(
        list = tests,
        times = 20
      )
```

```{r}
cached

autoplot(cached)

```

## With download


```{r}

clear <- function (fn) {
  function (search){fn(search); clear_package_cache()}
}

clear_package_cache()

uncached <- microbenchmark(
        clipr_all      = clear(test_A)("all"),
        clipr_parallel = clear(test_A)("parallel"),
        mice_all       = clear(test_B)("all"),
        mice_parallel  = clear(test_B)("parallel"),
        times = 5
      )
```

```{r}
uncached

autoplot(uncached)
```
