---
title: "apicheck Performance Tests"
author: "David Hugh-Jones <davidhughjones@gmail.com>"
date: "`r Sys.Date()`"
output: rmarkdown::html_document

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

# Speed tests

On my Macbook Air, standard broadband connection.


## Setup

```{r prepare, warning = FALSE, message = FALSE}
library(apicheck)
library(microbenchmark)
library(ggplot2)
library(dplyr)
library(huxtable)

options(repos = "https://cran.rstudio.com")

make_test <- function(fn, search, min_version = NA) {
  if (is.na(min_version)) min_version <- NULL
  bquote(when_fn_exists(.(fn), search = .(search), min_version = .(min_version), progress = FALSE))
}

print_results <- . %>% 
      mutate(date = as.character(date)) %>% 
      as_hux()                          %>% 
      add_colnames()                    %>% 
      set_bold(1, everywhere, TRUE)     %>% 
      set_outer_borders(0.4)            %>% 
      set_number_format(NA)

pretty_print <- . %>% 
      summary()                                          %>% 
      arrange(as.character(expr))                        %>% 
      as_hux()                                           %>% 
      add_colnames()                                     %>% 
      set_bold(1, everywhere, TRUE)                      %>% 
      set_background_color(evens, everywhere, grey(0.9)) %>% 
      set_outer_borders(0.4)                             %>% 
      set_number_format(everywhere, -matches("neval"), 1)

pretty_plot <- function (result) {
  autoplot(result) + 
       geom_point(color = "red", alpha = 0.5, size = 0.5) + 
        scale_x_discrete(limits = rev(sort(names(tests))))
}
```

## The tests

`clipr` is a small package with few versions. `mice` is a larger package which requires compilation, with more
dependencies.

```{r}
fns <- c("clipr::dr_clipr", "mice::ncc")
min_versions <- c(NA, "2.20")
args <- expand.grid(
        fn          = fns,
        search      = c("binary", "forward", "backward", "all", "parallel"), 
        stringsAsFactors = FALSE
      )
args$min_version <- min_versions[match(args$fn, fns)]

test_df <- args %>% rowwise %>% do(expr = make_test(.$fn, .$search, .$min_version)) %>% bind_cols(args) %>% mutate(label = paste(fn, search, sep = " / "))
tests <- test_df$expr
names(tests) <- test_df$label

noquote(as.character(tests))
```

## Results

Backward search should work well for both these functions.

```{r showresults}
set_lib_dir(".apicheck")
print_results(when_fn_exists("clipr::dr_clipr", search = "all"))
print_results(when_fn_exists("mice::ncc", search = "all", min_version = "2.20"))
```

## Pre-downloaded

```{r predownloaded, cache = TRUE}
# cache packages:
set_lib_dir(".apicheck")
invisible(mapply(when_fn_exists, fn = fns, min_version = ifelse(is.na(min_versions), "0.0", min_versions), search = "all"))


cached <- microbenchmark(
        list = tests,
        times = 20
      )
```

```{r printpredownloaded}

pretty_print(cached)
pretty_plot(cached)

```

## With download


```{r withdownload, eval = FALSE, cache = TRUE}

set_lib_dir(NULL)

tests2 <- lapply(tests, function (x) bquote(
  {.(x); clear_package_cache()})
)
names(tests2) <- names(tests)

uncached <- microbenchmark::microbenchmark(list = tests2, times = 5)

```

```{r printwithdownload, eval = FALSE}

pretty_print(uncached)
pretty_plot(uncached)

```
